server:
  port: 7777

invoicing-system:
  database: file
  database.directory: db
  database.invoices.file: invoices.txt
  database.id.file: id.txt

logging:
  level:
    org:
      springframework:
        boot: INFO
    ie:
      futurecollars:
        invoicing: WARN
        invoicing.db: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver