server:
  port: 7777

logging:
  level:
    org:
      springframework:
        boot: INFO
    ie:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  profiles:
    active: file
  flyway:
    enabled: false
  security:
    user:
      name: lei
      password: abc123

invoicing-system:
  allowedOrigins: http://localhost:4200
  csrf:
    disable: true