server:
  port: 7777

logging:
  level:
    org:
      springframework:
        boot: INFO
    ie:
      futurecollars:
        invoicing: WARN
        invoicing.db: DEBUG

spring:
  profiles:
    active: sql
  flyway:
    enabled: true