server:
  port: 7777

logging:
  level:
    org:
      springframework:
        boot: INFO
    ie:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  profiles:
    active: jpa-flyway
  flyway:
    enabled: false
