name: CI

on:
  push:
    branches: [lesson*]
  pull_request:
    branches: [lesson*]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with gradle
        run: ./gradlew build

